#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorProcedures
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LocalDoctorsAndProceduresDB")]
	public partial class DoctorProcedureClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDoctorsProcedure(DoctorsProcedure instance);
    partial void UpdateDoctorsProcedure(DoctorsProcedure instance);
    partial void DeleteDoctorsProcedure(DoctorsProcedure instance);
    #endregion
		
		public DoctorProcedureClassDataContext() : 
				base(global::DoctorProcedures.Properties.Settings.Default.LocalDoctorsAndProceduresDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DoctorProcedureClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DoctorProcedureClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DoctorProcedureClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DoctorProcedureClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DoctorsProcedure> DoctorsProcedures
		{
			get
			{
				return this.GetTable<DoctorsProcedure>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoctorsProcedures")]
	public partial class DoctorsProcedure : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _doctorName;
		
		private string _doctorID;
		
		private System.Nullable<decimal> _gloveSize;
		
		private string _procedureName;
		
		private string _modality;
		
		private string _patientOrientation;
		
		private string _ifBilateral;
		
		private System.Nullable<decimal> _syringes1mL;
		
		private System.Nullable<decimal> _syringes3mL;
		
		private System.Nullable<decimal> _syringes5mL;
		
		private System.Nullable<decimal> _syringes10mL;
		
		private System.Nullable<decimal> _needleDrawingUp;
		
		private System.Nullable<decimal> _needle25g;
		
		private System.Nullable<decimal> _needle19g;
		
		private System.Nullable<decimal> _needle22g50mm;
		
		private System.Nullable<decimal> _needle22g90mm;
		
		private string _contrast;
		
		private System.Nullable<decimal> _lignocaine;
		
		private System.Nullable<decimal> _bupivacaine;
		
		private string _steroidType;
		
		private System.Nullable<decimal> _steroidAmount;
		
		private string _otherEquipment;
		
		private string _comments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndoctorNameChanging(string value);
    partial void OndoctorNameChanged();
    partial void OndoctorIDChanging(string value);
    partial void OndoctorIDChanged();
    partial void OngloveSizeChanging(System.Nullable<decimal> value);
    partial void OngloveSizeChanged();
    partial void OnprocedureNameChanging(string value);
    partial void OnprocedureNameChanged();
    partial void OnmodalityChanging(string value);
    partial void OnmodalityChanged();
    partial void OnpatientOrientationChanging(string value);
    partial void OnpatientOrientationChanged();
    partial void OnifBilateralChanging(string value);
    partial void OnifBilateralChanged();
    partial void Onsyringes1mLChanging(System.Nullable<decimal> value);
    partial void Onsyringes1mLChanged();
    partial void Onsyringes3mLChanging(System.Nullable<decimal> value);
    partial void Onsyringes3mLChanged();
    partial void Onsyringes5mLChanging(System.Nullable<decimal> value);
    partial void Onsyringes5mLChanged();
    partial void Onsyringes10mLChanging(System.Nullable<decimal> value);
    partial void Onsyringes10mLChanged();
    partial void OnneedleDrawingUpChanging(System.Nullable<decimal> value);
    partial void OnneedleDrawingUpChanged();
    partial void Onneedle25gChanging(System.Nullable<decimal> value);
    partial void Onneedle25gChanged();
    partial void Onneedle19gChanging(System.Nullable<decimal> value);
    partial void Onneedle19gChanged();
    partial void Onneedle22g50mmChanging(System.Nullable<decimal> value);
    partial void Onneedle22g50mmChanged();
    partial void Onneedle22g90mmChanging(System.Nullable<decimal> value);
    partial void Onneedle22g90mmChanged();
    partial void OncontrastChanging(string value);
    partial void OncontrastChanged();
    partial void OnlignocaineChanging(System.Nullable<decimal> value);
    partial void OnlignocaineChanged();
    partial void OnbupivacaineChanging(System.Nullable<decimal> value);
    partial void OnbupivacaineChanged();
    partial void OnsteroidTypeChanging(string value);
    partial void OnsteroidTypeChanged();
    partial void OnsteroidAmountChanging(System.Nullable<decimal> value);
    partial void OnsteroidAmountChanged();
    partial void OnotherEquipmentChanging(string value);
    partial void OnotherEquipmentChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    #endregion
		
		public DoctorsProcedure()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doctorName", DbType="VarChar(50)")]
		public string doctorName
		{
			get
			{
				return this._doctorName;
			}
			set
			{
				if ((this._doctorName != value))
				{
					this.OndoctorNameChanging(value);
					this.SendPropertyChanging();
					this._doctorName = value;
					this.SendPropertyChanged("doctorName");
					this.OndoctorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doctorID", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string doctorID
		{
			get
			{
				return this._doctorID;
			}
			set
			{
				if ((this._doctorID != value))
				{
					this.OndoctorIDChanging(value);
					this.SendPropertyChanging();
					this._doctorID = value;
					this.SendPropertyChanged("doctorID");
					this.OndoctorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gloveSize", DbType="Decimal(2,1)")]
		public System.Nullable<decimal> gloveSize
		{
			get
			{
				return this._gloveSize;
			}
			set
			{
				if ((this._gloveSize != value))
				{
					this.OngloveSizeChanging(value);
					this.SendPropertyChanging();
					this._gloveSize = value;
					this.SendPropertyChanged("gloveSize");
					this.OngloveSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procedureName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string procedureName
		{
			get
			{
				return this._procedureName;
			}
			set
			{
				if ((this._procedureName != value))
				{
					this.OnprocedureNameChanging(value);
					this.SendPropertyChanging();
					this._procedureName = value;
					this.SendPropertyChanged("procedureName");
					this.OnprocedureNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modality", DbType="Char(2)")]
		public string modality
		{
			get
			{
				return this._modality;
			}
			set
			{
				if ((this._modality != value))
				{
					this.OnmodalityChanging(value);
					this.SendPropertyChanging();
					this._modality = value;
					this.SendPropertyChanged("modality");
					this.OnmodalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patientOrientation", DbType="VarChar(50)")]
		public string patientOrientation
		{
			get
			{
				return this._patientOrientation;
			}
			set
			{
				if ((this._patientOrientation != value))
				{
					this.OnpatientOrientationChanging(value);
					this.SendPropertyChanging();
					this._patientOrientation = value;
					this.SendPropertyChanged("patientOrientation");
					this.OnpatientOrientationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ifBilateral", DbType="VarChar(50)")]
		public string ifBilateral
		{
			get
			{
				return this._ifBilateral;
			}
			set
			{
				if ((this._ifBilateral != value))
				{
					this.OnifBilateralChanging(value);
					this.SendPropertyChanging();
					this._ifBilateral = value;
					this.SendPropertyChanged("ifBilateral");
					this.OnifBilateralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_syringes1mL", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> syringes1mL
		{
			get
			{
				return this._syringes1mL;
			}
			set
			{
				if ((this._syringes1mL != value))
				{
					this.Onsyringes1mLChanging(value);
					this.SendPropertyChanging();
					this._syringes1mL = value;
					this.SendPropertyChanged("syringes1mL");
					this.Onsyringes1mLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_syringes3mL", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> syringes3mL
		{
			get
			{
				return this._syringes3mL;
			}
			set
			{
				if ((this._syringes3mL != value))
				{
					this.Onsyringes3mLChanging(value);
					this.SendPropertyChanging();
					this._syringes3mL = value;
					this.SendPropertyChanged("syringes3mL");
					this.Onsyringes3mLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_syringes5mL", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> syringes5mL
		{
			get
			{
				return this._syringes5mL;
			}
			set
			{
				if ((this._syringes5mL != value))
				{
					this.Onsyringes5mLChanging(value);
					this.SendPropertyChanging();
					this._syringes5mL = value;
					this.SendPropertyChanged("syringes5mL");
					this.Onsyringes5mLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_syringes10mL", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> syringes10mL
		{
			get
			{
				return this._syringes10mL;
			}
			set
			{
				if ((this._syringes10mL != value))
				{
					this.Onsyringes10mLChanging(value);
					this.SendPropertyChanging();
					this._syringes10mL = value;
					this.SendPropertyChanged("syringes10mL");
					this.Onsyringes10mLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_needleDrawingUp", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> needleDrawingUp
		{
			get
			{
				return this._needleDrawingUp;
			}
			set
			{
				if ((this._needleDrawingUp != value))
				{
					this.OnneedleDrawingUpChanging(value);
					this.SendPropertyChanging();
					this._needleDrawingUp = value;
					this.SendPropertyChanged("needleDrawingUp");
					this.OnneedleDrawingUpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_needle25g", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> needle25g
		{
			get
			{
				return this._needle25g;
			}
			set
			{
				if ((this._needle25g != value))
				{
					this.Onneedle25gChanging(value);
					this.SendPropertyChanging();
					this._needle25g = value;
					this.SendPropertyChanged("needle25g");
					this.Onneedle25gChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_needle19g", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> needle19g
		{
			get
			{
				return this._needle19g;
			}
			set
			{
				if ((this._needle19g != value))
				{
					this.Onneedle19gChanging(value);
					this.SendPropertyChanging();
					this._needle19g = value;
					this.SendPropertyChanged("needle19g");
					this.Onneedle19gChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_needle22g50mm", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> needle22g50mm
		{
			get
			{
				return this._needle22g50mm;
			}
			set
			{
				if ((this._needle22g50mm != value))
				{
					this.Onneedle22g50mmChanging(value);
					this.SendPropertyChanging();
					this._needle22g50mm = value;
					this.SendPropertyChanged("needle22g50mm");
					this.Onneedle22g50mmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_needle22g90mm", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> needle22g90mm
		{
			get
			{
				return this._needle22g90mm;
			}
			set
			{
				if ((this._needle22g90mm != value))
				{
					this.Onneedle22g90mmChanging(value);
					this.SendPropertyChanging();
					this._needle22g90mm = value;
					this.SendPropertyChanged("needle22g90mm");
					this.Onneedle22g90mmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrast", DbType="VarChar(50)")]
		public string contrast
		{
			get
			{
				return this._contrast;
			}
			set
			{
				if ((this._contrast != value))
				{
					this.OncontrastChanging(value);
					this.SendPropertyChanging();
					this._contrast = value;
					this.SendPropertyChanged("contrast");
					this.OncontrastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lignocaine", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> lignocaine
		{
			get
			{
				return this._lignocaine;
			}
			set
			{
				if ((this._lignocaine != value))
				{
					this.OnlignocaineChanging(value);
					this.SendPropertyChanging();
					this._lignocaine = value;
					this.SendPropertyChanged("lignocaine");
					this.OnlignocaineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bupivacaine", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> bupivacaine
		{
			get
			{
				return this._bupivacaine;
			}
			set
			{
				if ((this._bupivacaine != value))
				{
					this.OnbupivacaineChanging(value);
					this.SendPropertyChanging();
					this._bupivacaine = value;
					this.SendPropertyChanged("bupivacaine");
					this.OnbupivacaineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_steroidType", DbType="VarChar(50)")]
		public string steroidType
		{
			get
			{
				return this._steroidType;
			}
			set
			{
				if ((this._steroidType != value))
				{
					this.OnsteroidTypeChanging(value);
					this.SendPropertyChanging();
					this._steroidType = value;
					this.SendPropertyChanged("steroidType");
					this.OnsteroidTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_steroidAmount", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> steroidAmount
		{
			get
			{
				return this._steroidAmount;
			}
			set
			{
				if ((this._steroidAmount != value))
				{
					this.OnsteroidAmountChanging(value);
					this.SendPropertyChanging();
					this._steroidAmount = value;
					this.SendPropertyChanged("steroidAmount");
					this.OnsteroidAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherEquipment", DbType="VarChar(500)")]
		public string otherEquipment
		{
			get
			{
				return this._otherEquipment;
			}
			set
			{
				if ((this._otherEquipment != value))
				{
					this.OnotherEquipmentChanging(value);
					this.SendPropertyChanging();
					this._otherEquipment = value;
					this.SendPropertyChanged("otherEquipment");
					this.OnotherEquipmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="VarChar(500)")]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
