#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorProcedures
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LocalDoctorsAndProceduresDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDoctor(Doctor instance);
    partial void UpdateDoctor(Doctor instance);
    partial void DeleteDoctor(Doctor instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DoctorProcedures.Properties.Settings.Default.LocalDoctorsAndProceduresDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Doctor> Doctors
		{
			get
			{
				return this.GetTable<Doctor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Doctors")]
	public partial class Doctor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _doctorID;
		
		private string _doctorName;
		
		private System.Nullable<decimal> _gloveSize;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndoctorIDChanging(string value);
    partial void OndoctorIDChanged();
    partial void OndoctorNameChanging(string value);
    partial void OndoctorNameChanged();
    partial void OngloveSizeChanging(System.Nullable<decimal> value);
    partial void OngloveSizeChanged();
    #endregion
		
		public Doctor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doctorID", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string doctorID
		{
			get
			{
				return this._doctorID;
			}
			set
			{
				if ((this._doctorID != value))
				{
					this.OndoctorIDChanging(value);
					this.SendPropertyChanging();
					this._doctorID = value;
					this.SendPropertyChanged("doctorID");
					this.OndoctorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doctorName", DbType="VarChar(50)")]
		public string doctorName
		{
			get
			{
				return this._doctorName;
			}
			set
			{
				if ((this._doctorName != value))
				{
					this.OndoctorNameChanging(value);
					this.SendPropertyChanging();
					this._doctorName = value;
					this.SendPropertyChanged("doctorName");
					this.OndoctorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gloveSize", DbType="Decimal(2,1)")]
		public System.Nullable<decimal> gloveSize
		{
			get
			{
				return this._gloveSize;
			}
			set
			{
				if ((this._gloveSize != value))
				{
					this.OngloveSizeChanging(value);
					this.SendPropertyChanging();
					this._gloveSize = value;
					this.SendPropertyChanged("gloveSize");
					this.OngloveSizeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
