<?xml version="1.0" encoding="utf-8"?><Database Name="LocalDoctorsAndProceduresDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\mssqllocaldb;AttachDbFilename=|DataDirectory|\LocalDoctorsAndProceduresDB.mdf;Integrated Security=True" SettingsObjectName="DoctorProcedures.Properties.Settings" SettingsPropertyName="LocalDoctorsAndProceduresDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Doctors" Member="Doctors">
    <Type Name="Doctor">
      <Column Name="doctorID" Type="System.String" DbType="Char(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="doctorName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="gloveSize" Type="System.Decimal" DbType="Decimal(2,1)" CanBeNull="true" />
    </Type>
  </Table>
</Database>