#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorProcedures
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LocalDoctorsAndProceduresDB")]
	public partial class ModalitiesClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertModality(Modality instance);
    partial void UpdateModality(Modality instance);
    partial void DeleteModality(Modality instance);
    #endregion
		
		public ModalitiesClassDataContext() : 
				base(global::DoctorProcedures.Properties.Settings.Default.LocalDoctorsAndProceduresDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModalitiesClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModalitiesClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModalitiesClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModalitiesClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Modality> Modalities
		{
			get
			{
				return this.GetTable<Modality>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Modalities")]
	public partial class Modality : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _modalityID;
		
		private string _modalityName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmodalityIDChanging(string value);
    partial void OnmodalityIDChanged();
    partial void OnmodalityNameChanging(string value);
    partial void OnmodalityNameChanged();
    #endregion
		
		public Modality()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modalityID", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string modalityID
		{
			get
			{
				return this._modalityID;
			}
			set
			{
				if ((this._modalityID != value))
				{
					this.OnmodalityIDChanging(value);
					this.SendPropertyChanging();
					this._modalityID = value;
					this.SendPropertyChanged("modalityID");
					this.OnmodalityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modalityName", DbType="VarChar(50)")]
		public string modalityName
		{
			get
			{
				return this._modalityName;
			}
			set
			{
				if ((this._modalityName != value))
				{
					this.OnmodalityNameChanging(value);
					this.SendPropertyChanging();
					this._modalityName = value;
					this.SendPropertyChanged("modalityName");
					this.OnmodalityNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
